package utils.message;

public enum WHGPMessageType {
    INITIALIZE_GAME,
    SET_GAME_INFO,
    GET_GAME_INFO, GET_TILE_GRID,
    JOIN_REQUEST,
    START_GAME,
    SEND_WORD,
    PLAYER_JOINED, USERNAME_EXIST, GAME_IS_STARTED, MAX_PLAYER_LIMIT,
    WORD_REJECTED,
    PLAYER_LEFT, PLAYER_LIST,
    NUMBER_OF_GAMES_WON,
    CURRENT_SCORES, CURRENT_PLAYER,
    WINNER_OF_ROUND, WINNER_OF_GAME
}
