public enum WHGPMessageType {
    JOIN_REQUEST, WORD,
    JOINED_PLAYER, USERNAME_EXIST, GAME_IS_STARTED, MAX_PLAYER_LIMIT,
    WORD_ACCEPTED, WORD_REJECTED,
    PLAYER_LEFT, PLAYER_LIST,
    NUMBER_OF_GAMES_WON,
    CURRENT_SCORES, CURRENT_PLAYER,
    WINNER_OF_ROUND, WINNER_OF_GAME
}
